export const ROUTER = {
    HOME: '',
    LISTROOM: '/listRoom',
    BOOKINGROOM: '/bookingRoom/:id',
    ABOUT: '/about',
    CONTACT: '/contact',
    LOGIN: '/login',
    REGISTER: '/register',
    PROFILE: '/profile',
    DASHBOARD: '/dashboard',
    NEWBOOKED: '/bookings/newBooked',
    PROFILEBOOKINGS : '/bookings/profileBookings',
    PAYMENTCONFIRM:'/bookings/paymentConfirm',
    ROOMS : '/rooms',
    GUESTS : '/guests',
    REPORT : '/report',
    INFOCUSTOMER: '/booking/:id/infoCustomer',
    PAYMENTCUSTOMER: '/paymentCustomer/:id',
}