export const ROUTER = {
    HOME: '',
    LISTROOM: '/listRoom',
    BOOKINGROOM: '/bookingRoom/:id',
    ABOUT: '/about',
    CONTACT: '/contact',
    LOGIN: '/login',
    REGISTER: '/register',
    PROFILE: '/profile',
    DASHBOARD: '/dashboard',
    NEWBOOKED: '/bookings/newBooked',
    PROFILEBOOKINGS : '/bookings/profileBookings',
    PAYMENTCONFIRM:'/bookings/paymentConfirm',
    GUESTS : '/guests',
    REPORT : '/report',
    INFOCUSTOMER: '/booking/infoCustomer',
    PAYMENTCUSTOMER: '/paymentCustomer',
    HISTORYBOOKING: '/historyBooking',
    DETAILBOOKING: '/detailBooking',
    ROOMMANAGE: '/roomManage',
    SERVICEMANAGE: '/serviceManage',
    ROOMEDIT: '/roomEdit',
}