export const ROUTER = {
    HOME: '',
    ROOMS: '/rooms',
    ABOUT: '/about',
    CONTACT: '/contact',
    LOGIN: '/login',
    REGISTER: '/register',
    PROFILE: '/profile',
    DASHBOARD: '/dashboard',
    NEWBOOKED: '/bookings/newBooked',
    PROFILEBOOKINGS : '/bookings/profileBookings',
    PAYMENTCONFIRM:'/bookings/paymentConfirm',
    ROOMS : '/rooms',
    GUESTS : '/guests',
    REPORT : '/report',
}